version: '3.5'
name: 'flucks'

# Définition des réseaux
networks:
  traefik_web:
    external: true
  flucks:
    driver: bridge

# Définition des services
services:
  app:
    build:
      context: ../application/
      target: dev
    volumes:
      - ../application:/app
    working_dir: /app
    networks:
      - flucks.net
      - traefik_web
    environment:
      - NODE_ENV=development
    ports:
      - '35300:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flucks.rule=Host(`flucks.timeuh.fr:35300`)"
      - "traefik.http.routers.flucks.entrypoints=websecure"
      - "traefik.http.routers.flucks.tls.certresolver=myresolver"
      - "traefik.http.services.flucks.loadbalancer.server.port=3000"


  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '35301:8080'
    networks:
      - flucks
      - traefik_web

  flucks.db:
    image: 'postgres:latest'
    env_file: ./db.env
    ports:
      - '35302:5432'
    networks:
      - flucks

  webrtc:
    image: 'node:alpine'
    ports:
      - '35303:3000'
    env_file:
      - express.env
    command: sh -c "npm i && npm run start"
    volumes:
      - ../server:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - flucks
    environment:
      - NODE_ENV=development

  api:
    image: 'node:alpine'
    ports:
      - '35305:3000'
    command: sh -c "npm i && npm run dev"
    volumes:
      - ../api:/app
    working_dir: /app
    networks:
      - flucks
    environment:
      - NODE_ENV=development
