version: '3'
networks:
  flucks.net:
    driver: bridge
services:
  flucks.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: db.env
    ports:
      - '3306:3306'
    networks:
      - flucks.net

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - flucks.net
